// Generated by Haxe 3.4.4
(function ($hx_exports) { "use strict";
var GeometryXD = $hx_exports["GeometryXD"] = function() { };
GeometryXD.__name__ = true;
GeometryXD.main = function() {
	console.log("GeometryXD");
};
GeometryXD.prototype = {
	positive_inside_I: function(a) {
		var _g = 0;
		while(_g < a.length) {
			var i = a[_g];
			++_g;
			if(i > 0) {
				return true;
			}
		}
		return false;
	}
	,zero_inside_I: function(a) {
		var _g = 0;
		while(_g < a.length) {
			var i = a[_g];
			++_g;
			if(i == 0) {
				return true;
			}
		}
		return false;
	}
	,negative_inside_I: function(a) {
		var _g = 0;
		while(_g < a.length) {
			var i = a[_g];
			++_g;
			if(i < 0) {
				return true;
			}
		}
		return false;
	}
	,positive_inside_F: function(a) {
		var _g = 0;
		while(_g < a.length) {
			var i = a[_g];
			++_g;
			if(i > 0) {
				return true;
			}
		}
		return false;
	}
	,zero_inside_F: function(a) {
		var _g = 0;
		while(_g < a.length) {
			var i = a[_g];
			++_g;
			if(i == 0) {
				return true;
			}
		}
		return false;
	}
	,negative_inside_F: function(a) {
		var _g = 0;
		while(_g < a.length) {
			var i = a[_g];
			++_g;
			if(i < 0) {
				return true;
			}
		}
		return false;
	}
	,sum_I: function(a) {
		var rez = 0;
		var _g1 = 0;
		var _g = a.length;
		while(_g1 < _g) {
			var i = _g1++;
			rez += i;
		}
		return rez;
	}
	,sum_F: function(a) {
		var rez = 0;
		var _g1 = 0;
		var _g = a.length;
		while(_g1 < _g) {
			var i = _g1++;
			rez += i;
		}
		return rez;
	}
	,diff_I: function(a) {
		var rez = a[0];
		var _g1 = 1;
		var _g = a.length;
		while(_g1 < _g) {
			var i = _g1++;
			rez -= i;
		}
		return rez;
	}
	,diff_F: function(a) {
		var rez = a[0];
		var _g1 = 1;
		var _g = a.length;
		while(_g1 < _g) {
			var i = _g1++;
			rez -= i;
		}
		return rez;
	}
	,middle_F: function(a) {
		return this.sum_F(a) / a.length;
	}
	,multiply_FperF: function(a,n) {
		var _g = [];
		var _g2 = 0;
		var _g1 = a.length;
		while(_g2 < _g1) {
			var i = _g2++;
			_g.push(a[i] * n);
		}
		return _g;
	}
	,multiply_I: function(a) {
		var rez = a[0];
		var _g1 = 1;
		var _g = a.length;
		while(_g1 < _g) {
			var i = _g1++;
			rez *= i;
		}
		return rez;
	}
	,multiply_F: function(a) {
		var rez = a[0];
		var _g1 = 1;
		var _g = a.length;
		while(_g1 < _g) {
			var i = _g1++;
			rez *= i;
		}
		return rez;
	}
	,minus_I: function(a) {
		var _g = [];
		var _g2 = 0;
		var _g1 = a.length;
		while(_g2 < _g1) {
			var i = _g2++;
			_g.push(-a[i]);
		}
		return _g;
	}
	,minus_F: function(a) {
		var _g = [];
		var _g2 = 0;
		var _g1 = a.length;
		while(_g2 < _g1) {
			var i = _g2++;
			_g.push(-a[i]);
		}
		return _g;
	}
	,sum_xI: function(a) {
		var _g = [];
		var _g2 = 0;
		var _g1 = a[0].length;
		while(_g2 < _g1) {
			var i = _g2++;
			var _g3 = [];
			var _g5 = 0;
			var _g4 = a.length;
			while(_g5 < _g4) {
				var ai = _g5++;
				_g3.push(a[ai][i]);
			}
			_g.push(this.sum_I(_g3));
		}
		return _g;
	}
	,sum_xF: function(a) {
		var _g = [];
		var _g2 = 0;
		var _g1 = a[0].length;
		while(_g2 < _g1) {
			var i = _g2++;
			var _g3 = [];
			var _g5 = 0;
			var _g4 = a.length;
			while(_g5 < _g4) {
				var ai = _g5++;
				_g3.push(a[ai][i]);
			}
			_g.push(this.sum_F(_g3));
		}
		return _g;
	}
	,diff_xI: function(a) {
		var _g = [];
		var _g2 = 0;
		var _g1 = a[0].length;
		while(_g2 < _g1) {
			var i = _g2++;
			var _g3 = [];
			var _g5 = 0;
			var _g4 = a.length;
			while(_g5 < _g4) {
				var ai = _g5++;
				_g3.push(a[ai][i]);
			}
			_g.push(this.diff_I(_g3));
		}
		return _g;
	}
	,diff_xF: function(a) {
		var _g = [];
		var _g2 = 0;
		var _g1 = a[0].length;
		while(_g2 < _g1) {
			var i = _g2++;
			var _g3 = [];
			var _g5 = 0;
			var _g4 = a.length;
			while(_g5 < _g4) {
				var ai = _g5++;
				_g3.push(a[ai][i]);
			}
			_g.push(this.diff_F(_g3));
		}
		return _g;
	}
	,middle_xF: function(a) {
		var _g = [];
		var _g2 = 0;
		var _g1 = a[0].length;
		while(_g2 < _g1) {
			var i = _g2++;
			var _g3 = [];
			var _g5 = 0;
			var _g4 = a.length;
			while(_g5 < _g4) {
				var ai = _g5++;
				_g3.push(a[ai][i]);
			}
			_g.push(this.middle_F(_g3));
		}
		return _g;
	}
	,multiply_xFperF: function(a,n) {
		var _g = [];
		var _g2 = 0;
		var _g1 = a.length;
		while(_g2 < _g1) {
			var i = _g2++;
			_g.push(this.multiply_FperF(a[i],n));
		}
		return _g;
	}
	,multiply_xI: function(a) {
		var _g = [];
		var _g2 = 0;
		var _g1 = a[0].length;
		while(_g2 < _g1) {
			var i = _g2++;
			var _g3 = [];
			var _g5 = 0;
			var _g4 = a.length;
			while(_g5 < _g4) {
				var ai = _g5++;
				_g3.push(a[ai][i]);
			}
			_g.push(this.multiply_I(_g3));
		}
		return _g;
	}
	,multiply_xF: function(a) {
		var _g = [];
		var _g2 = 0;
		var _g1 = a[0].length;
		while(_g2 < _g1) {
			var i = _g2++;
			var _g3 = [];
			var _g5 = 0;
			var _g4 = a.length;
			while(_g5 < _g4) {
				var ai = _g5++;
				_g3.push(a[ai][i]);
			}
			_g.push(this.multiply_F(_g3));
		}
		return _g;
	}
	,multisum_xI: function(a) {
		return this.sum_I(this.multiply_xI(a));
	}
	,multisum_xF: function(a) {
		return this.sum_F(this.multiply_xF(a));
	}
	,sum_previous_I: function(a) {
		var _g = [];
		var _g2 = 0;
		var _g1 = a.length;
		while(_g2 < _g1) {
			var i = _g2++;
			_g.push(i == 0 ? a[i] : a[i] + a[i - 1]);
		}
		return _g;
	}
	,diff_previous_I: function(a) {
		var _g = [];
		var _g2 = 0;
		var _g1 = a.length;
		while(_g2 < _g1) {
			var i = _g2++;
			_g.push(i == 0 ? a[i] : a[i] - a[i - 1]);
		}
		return _g;
	}
	,sum_before_I: function(a) {
		var rez = [];
		var x = 0;
		var _g1 = 0;
		var _g = a.length;
		while(_g1 < _g) {
			var i = _g1++;
			x += a[i];
			rez.push(x);
		}
		return rez;
	}
	,diff_before_I: function(a) {
		var rez = [a[0]];
		var _g1 = 1;
		var _g = a.length;
		while(_g1 < _g) {
			var i = _g1++;
			rez.push(a[i] - a[i - 1]);
		}
		return rez;
	}
	,sum_previous_F: function(a) {
		var _g = [];
		var _g2 = 0;
		var _g1 = a.length;
		while(_g2 < _g1) {
			var i = _g2++;
			_g.push(i == 0 ? a[i] : a[i] + a[i - 1]);
		}
		return _g;
	}
	,diff_previous_F: function(a) {
		var _g = [];
		var _g2 = 0;
		var _g1 = a.length;
		while(_g2 < _g1) {
			var i = _g2++;
			_g.push(i == 0 ? a[i] : a[i] - a[i - 1]);
		}
		return _g;
	}
	,sum_before_F: function(a) {
		var rez = [];
		var x = 0;
		var _g1 = 0;
		var _g = a.length;
		while(_g1 < _g) {
			var i = _g1++;
			x += a[i];
			rez.push(x);
		}
		return rez;
	}
	,diff_before_F: function(a) {
		var rez = [a[0]];
		var _g1 = 1;
		var _g = a.length;
		while(_g1 < _g) {
			var i = _g1++;
			rez.push(a[i] - a[i - 1]);
		}
		return rez;
	}
	,recounter_I_F: function(what) {
		var rez = [];
		var _g = [];
		var _g2 = 0;
		var _g1 = what.length;
		while(_g2 < _g1) {
			var i = _g2++;
			_g.push(rez.push(what[i]));
		}
		return _g;
	}
	,recounter_F_I: function(what) {
		var rez = [];
		var _g = [];
		var _g2 = 0;
		var _g1 = what.length;
		while(_g2 < _g1) {
			var i = _g2++;
			_g.push(rez.push(what[i] | 0));
		}
		return _g;
	}
	,recounter_I_S: function(what) {
		var rez = [];
		var _g = [];
		var _g2 = 0;
		var _g1 = what.length;
		while(_g2 < _g1) {
			var i = _g2++;
			_g.push(Std.string(what[i]));
		}
		rez = _g;
		return rez;
	}
	,recounter_F_S: function(what) {
		var rez = [];
		var _g = [];
		var _g2 = 0;
		var _g1 = what.length;
		while(_g2 < _g1) {
			var i = _g2++;
			_g.push(Std.string(what[i]));
		}
		rez = _g;
		return rez;
	}
	,recounter_S_I: function(what) {
		var rez = [];
		var _g = [];
		var _g2 = 0;
		var _g1 = what.length;
		while(_g2 < _g1) {
			var i = _g2++;
			_g.push(Std.parseInt(what[i]));
		}
		rez = _g;
		return rez;
	}
	,recounter_S_F: function(what) {
		var rez = [];
		var _g = [];
		var _g2 = 0;
		var _g1 = what.length;
		while(_g2 < _g1) {
			var i = _g2++;
			_g.push(parseFloat(what[i]));
		}
		rez = _g;
		return rez;
	}
	,repeater_F_F: function(n,what,full) {
		if(full == null) {
			full = false;
		}
		var rez = null;
		if(n == 0) {
			return rez;
		}
		var wl = what.length;
		rez = [];
		if(wl == 0) {
			return rez;
		}
		if(n < 0) {
			what.reverse();
			n = Math.abs(n) | 0;
		}
		var ind = full ? n : Math.ceil(n / wl);
		var _g = [];
		var _g2 = 0;
		var _g1 = ind;
		while(_g2 < _g1) {
			var _ = _g2++;
			var _g4 = 0;
			var _g3 = wl;
			while(_g4 < _g3) {
				var i = _g4++;
				_g.push(what[i]);
			}
		}
		rez = _g;
		if(!full) {
			rez = rez.slice(0,n);
		}
		return rez;
	}
	,repeater_I_I: function(n,what,full) {
		if(full == null) {
			full = false;
		}
		var rez = null;
		if(n == 0) {
			return rez;
		}
		var wl = what.length;
		rez = [];
		if(wl == 0) {
			return rez;
		}
		if(n < 0) {
			what.reverse();
			n = Math.abs(n) | 0;
		}
		var ind = full ? n : Math.ceil(n / wl);
		var _g = [];
		var _g2 = 0;
		var _g1 = ind;
		while(_g2 < _g1) {
			var _ = _g2++;
			var _g4 = 0;
			var _g3 = wl;
			while(_g4 < _g3) {
				var i = _g4++;
				_g.push(what[i]);
			}
		}
		rez = _g;
		if(!full) {
			rez = rez.slice(0,n);
		}
		return rez;
	}
	,repeater_S_S: function(n,what,full) {
		if(full == null) {
			full = false;
		}
		var rez = null;
		if(n == 0) {
			return rez;
		}
		var wl = what.length;
		rez = [];
		if(wl == 0) {
			return rez;
		}
		if(n < 0) {
			what.reverse();
			n = Math.abs(n) | 0;
		}
		var ind = full ? n : Math.ceil(n / wl);
		var _g = [];
		var _g2 = 0;
		var _g1 = ind;
		while(_g2 < _g1) {
			var _ = _g2++;
			var _g4 = 0;
			var _g3 = wl;
			while(_g4 < _g3) {
				var i = _g4++;
				_g.push(what[i]);
			}
		}
		rez = _g;
		if(!full) {
			rez = rez.slice(0,n);
		}
		return rez;
	}
	,repeater_F_I: function(n,what_,full) {
		if(full == null) {
			full = false;
		}
		var rez = null;
		var what = this.recounter_F_I(what_);
		if(n == 0) {
			return rez;
		}
		var wl = what.length;
		rez = [];
		if(wl == 0) {
			return rez;
		}
		if(n < 0) {
			what.reverse();
			n = Math.abs(n) | 0;
		}
		var ind = full ? n : Math.ceil(n / wl);
		var _g = [];
		var _g2 = 0;
		var _g1 = ind;
		while(_g2 < _g1) {
			var _ = _g2++;
			var _g4 = 0;
			var _g3 = wl;
			while(_g4 < _g3) {
				var i = _g4++;
				_g.push(what[i]);
			}
		}
		rez = _g;
		if(!full) {
			rez = rez.slice(0,n);
		}
		return rez;
	}
	,repeater_S_I: function(n,what_,full) {
		if(full == null) {
			full = false;
		}
		var rez = null;
		var what = this.recounter_S_I(what_);
		if(n == 0) {
			return rez;
		}
		var wl = what.length;
		rez = [];
		if(wl == 0) {
			return rez;
		}
		if(n < 0) {
			what.reverse();
			n = Math.abs(n) | 0;
		}
		var ind = full ? n : Math.ceil(n / wl);
		var _g = [];
		var _g2 = 0;
		var _g1 = ind;
		while(_g2 < _g1) {
			var _ = _g2++;
			var _g4 = 0;
			var _g3 = wl;
			while(_g4 < _g3) {
				var i = _g4++;
				_g.push(what[i]);
			}
		}
		rez = _g;
		if(!full) {
			rez = rez.slice(0,n);
		}
		return rez;
	}
	,repeater_I_F: function(n,what_,full) {
		if(full == null) {
			full = false;
		}
		var rez = null;
		var what = this.recounter_I_F(what_);
		if(n == 0) {
			return rez;
		}
		var wl = what.length;
		rez = [];
		if(wl == 0) {
			return rez;
		}
		if(n < 0) {
			what.reverse();
			n = Math.abs(n) | 0;
		}
		var ind = full ? n : Math.ceil(n / wl);
		var _g = [];
		var _g2 = 0;
		var _g1 = ind;
		while(_g2 < _g1) {
			var _ = _g2++;
			var _g4 = 0;
			var _g3 = wl;
			while(_g4 < _g3) {
				var i = _g4++;
				_g.push(what[i]);
			}
		}
		rez = _g;
		if(!full) {
			rez = rez.slice(0,n);
		}
		return rez;
	}
	,repeater_S_F: function(n,what_,full) {
		if(full == null) {
			full = false;
		}
		var rez = null;
		var what = this.recounter_S_F(what_);
		if(n == 0) {
			return rez;
		}
		var wl = what.length;
		rez = [];
		if(wl == 0) {
			return rez;
		}
		if(n < 0) {
			what.reverse();
			n = Math.abs(n) | 0;
		}
		var ind = full ? n : Math.ceil(n / wl);
		var _g = [];
		var _g2 = 0;
		var _g1 = ind;
		while(_g2 < _g1) {
			var _ = _g2++;
			var _g4 = 0;
			var _g3 = wl;
			while(_g4 < _g3) {
				var i = _g4++;
				_g.push(what[i]);
			}
		}
		rez = _g;
		if(!full) {
			rez = rez.slice(0,n);
		}
		return rez;
	}
	,repeater_I_S: function(n,what_,full) {
		if(full == null) {
			full = false;
		}
		var rez = null;
		var what = this.recounter_I_S(what_);
		if(n == 0) {
			return rez;
		}
		var wl = what.length;
		rez = [];
		if(wl == 0) {
			return rez;
		}
		if(n < 0) {
			what.reverse();
			n = Math.abs(n) | 0;
		}
		var ind = full ? n : Math.ceil(n / wl);
		var _g = [];
		var _g2 = 0;
		var _g1 = ind;
		while(_g2 < _g1) {
			var _ = _g2++;
			var _g4 = 0;
			var _g3 = wl;
			while(_g4 < _g3) {
				var i = _g4++;
				_g.push(what[i]);
			}
		}
		rez = _g;
		if(!full) {
			rez = rez.slice(0,n);
		}
		return rez;
	}
	,repeater_F_S: function(n,what_,full) {
		if(full == null) {
			full = false;
		}
		var rez = null;
		var what = this.recounter_F_S(what_);
		if(n == 0) {
			return rez;
		}
		var wl = what.length;
		rez = [];
		if(wl == 0) {
			return rez;
		}
		if(n < 0) {
			what.reverse();
			n = Math.abs(n) | 0;
		}
		var ind = full ? n : Math.ceil(n / wl);
		var _g = [];
		var _g2 = 0;
		var _g1 = ind;
		while(_g2 < _g1) {
			var _ = _g2++;
			var _g4 = 0;
			var _g3 = wl;
			while(_g4 < _g3) {
				var i = _g4++;
				_g.push(what[i]);
			}
		}
		rez = _g;
		if(!full) {
			rez = rez.slice(0,n);
		}
		return rez;
	}
	,an_in_b_S: function(a,b) {
		var rez = null;
		var _g1 = 0;
		var _g = a.length;
		while(_g1 < _g) {
			var ia = _g1++;
			var _g3 = 0;
			var _g2 = b.length;
			while(_g3 < _g2) {
				var ib = _g3++;
				if(a[ia] == b[ib]) {
					rez.push([ia,ib]);
				}
			}
		}
		return rez;
	}
	,an_in_bn_S: function(a,b) {
		var rez = null;
		var _g1 = 0;
		var _g = a.length;
		while(_g1 < _g) {
			var ia = _g1++;
			var _g3 = 0;
			var _g2 = b.length;
			while(_g3 < _g2) {
				var ib = _g3++;
				var _g5 = 0;
				var _g4 = b[ib].length;
				while(_g5 < _g4) {
					var ibn = _g5++;
					if(a[ia] == b[ib][ibn]) {
						rez.push([ia,ib,ibn]);
					}
				}
			}
		}
		return rez;
	}
	,an_in_b_I: function(a,b) {
		var rez = null;
		var _g1 = 0;
		var _g = a.length;
		while(_g1 < _g) {
			var ia = _g1++;
			var _g3 = 0;
			var _g2 = b.length;
			while(_g3 < _g2) {
				var ib = _g3++;
				if(a[ia] == b[ib]) {
					rez.push([ia,ib]);
				}
			}
		}
		return rez;
	}
	,an_in_bn_I: function(a,b) {
		var rez = null;
		var _g1 = 0;
		var _g = a.length;
		while(_g1 < _g) {
			var ia = _g1++;
			var _g3 = 0;
			var _g2 = b.length;
			while(_g3 < _g2) {
				var ib = _g3++;
				var _g5 = 0;
				var _g4 = b[ib].length;
				while(_g5 < _g4) {
					var ibn = _g5++;
					if(a[ia] == b[ib][ibn]) {
						rez.push([ia,ib,ibn]);
					}
				}
			}
		}
		return rez;
	}
	,an_in_b_F: function(a,b) {
		var rez = null;
		var _g1 = 0;
		var _g = a.length;
		while(_g1 < _g) {
			var ia = _g1++;
			var _g3 = 0;
			var _g2 = b.length;
			while(_g3 < _g2) {
				var ib = _g3++;
				if(a[ia] == b[ib]) {
					rez.push([ia,ib]);
				}
			}
		}
		return rez;
	}
	,an_in_bn_F: function(a,b) {
		var rez = null;
		var _g1 = 0;
		var _g = a.length;
		while(_g1 < _g) {
			var ia = _g1++;
			var _g3 = 0;
			var _g2 = b.length;
			while(_g3 < _g2) {
				var ib = _g3++;
				var _g5 = 0;
				var _g4 = b[ib].length;
				while(_g5 < _g4) {
					var ibn = _g5++;
					if(a[ia] == b[ib][ibn]) {
						rez.push([ia,ib,ibn]);
					}
				}
			}
		}
		return rez;
	}
	,chain_indexes: function(a_l,n,ring) {
		var rez = null;
		if(n > a_l || n < 1) {
			return rez;
		}
		var ind = [];
		if(ring) {
			var _g = [];
			var _g1 = 0;
			while(_g1 < 2) {
				var b = _g1++;
				var _g3 = 0;
				var _g2 = a_l;
				while(_g3 < _g2) {
					var i = _g3++;
					var ind1;
					if(b < 1) {
						ind1 = i;
					} else if(i < n - 1) {
						ind1 = i;
					} else {
						continue;
					}
					_g.push(ind1);
				}
			}
			ind = _g;
		} else {
			var _g4 = [];
			var _g21 = 0;
			var _g11 = 1 + a_l - n;
			while(_g21 < _g11) {
				var i1 = _g21++;
				_g4.push(i1);
			}
			ind = _g4;
		}
		return rez;
	}
	,chain_S: function(a,n,ring) {
		if(ring == null) {
			ring = false;
		}
		var rez = null;
		var a_l = a.length;
		if(n > a_l || n < 1) {
			return rez;
		}
		var ind = this.chain_indexes(a_l,n,ring);
		var _g = [];
		var _g2 = 0;
		var _g1 = ind.length;
		while(_g2 < _g1) {
			var i = _g2++;
			var _g3 = [];
			var _g5 = 0;
			var _g4 = n;
			while(_g5 < _g4) {
				var j = _g5++;
				_g3.push(a[ind[i][j]]);
			}
			_g.push(_g3);
		}
		rez = _g;
		return rez;
	}
	,chain_I: function(a,n,ring) {
		if(ring == null) {
			ring = false;
		}
		var rez = null;
		var a_l = a.length;
		if(n > a_l || n < 1) {
			return rez;
		}
		var ind = this.chain_indexes(a_l,n,ring);
		var _g = [];
		var _g2 = 0;
		var _g1 = ind.length;
		while(_g2 < _g1) {
			var i = _g2++;
			var _g3 = [];
			var _g5 = 0;
			var _g4 = n;
			while(_g5 < _g4) {
				var j = _g5++;
				_g3.push(a[ind[i][j]]);
			}
			_g.push(_g3);
		}
		rez = _g;
		return rez;
	}
	,chain_F: function(a,n,ring) {
		if(ring == null) {
			ring = false;
		}
		var rez = null;
		var a_l = a.length;
		if(n > a_l || n < 1) {
			return rez;
		}
		var ind = this.chain_indexes(a_l,n,ring);
		var _g = [];
		var _g2 = 0;
		var _g1 = ind.length;
		while(_g2 < _g1) {
			var i = _g2++;
			var _g3 = [];
			var _g5 = 0;
			var _g4 = n;
			while(_g5 < _g4) {
				var j = _g5++;
				_g3.push(a[ind[i][j]]);
			}
			_g.push(_g3);
		}
		rez = _g;
		return rez;
	}
	,steps_internal: function(xmin,xmax,n,borders) {
		if(borders == null) {
			borders = false;
		}
		var rez = null;
		if(n < 1) {
			return rez;
		}
		var st = (xmax - xmin) / (n + 1);
		if(borders) {
			var _g = [];
			var _g2 = 0;
			var _g1 = n + 2;
			while(_g2 < _g1) {
				var i = _g2++;
				_g.push(i > 0 && i < n + 1 ? xmin + st * i : i == 0 ? xmin : xmax);
			}
			rez = _g;
		} else {
			var _g3 = [];
			var _g21 = 1;
			var _g11 = n + 1;
			while(_g21 < _g11) {
				var i1 = _g21++;
				_g3.push(xmin + st * i1);
			}
			rez = _g3;
		}
		return rez;
	}
	,steps_external: function(smin,smax,n,direction) {
		var rez = null;
		if(n < 1 || direction < -1 || direction > 1) {
			return rez;
		}
		var st = smax - smin;
		if(direction > 0) {
			var _g = [];
			var _g2 = 0;
			var _g1 = n + 2;
			while(_g2 < _g1) {
				var i = _g2++;
				_g.push(smin + st * i);
			}
			rez = _g;
		} else if(direction < 0) {
			var full = smin - st * n;
			var _g3 = [];
			var _g21 = 0;
			var _g11 = n + 2;
			while(_g21 < _g11) {
				var i1 = _g21++;
				_g3.push(full + st * i1);
			}
			rez = _g3;
		} else {
			var full1 = smin - st * n;
			var _g4 = [];
			var _g12 = 0;
			while(_g12 < 2) {
				var b = _g12++;
				var _g31 = 0;
				var _g22 = n + 2;
				while(_g31 < _g22) {
					var i2 = _g31++;
					var rez1;
					if(b == 0) {
						rez1 = full1 + st * i2;
					} else if(i2 > 1) {
						rez1 = smin + st * i2;
					} else {
						continue;
					}
					_g4.push(rez1);
				}
			}
			rez = _g4;
		}
		return rez;
	}
	,sin_cos_cut: function(x) {
		if(x > 1) {
			return 1;
		} else if(x < -1) {
			return -1;
		} else {
			return x;
		}
	}
	,degrees: function(angle) {
		return angle * 180 / Math.PI;
	}
	,radians: function(angle) {
		return angle / 180 * Math.PI;
	}
	,angle_quadrant: function(angle,rad) {
		if(rad == null) {
			rad = false;
		}
		var k = 4;
		if(rad) {
			angle = this.degrees(angle);
		}
		var x = angle % 360;
		if(x > 270) {
			k = 4;
		} else if(x > 180) {
			k = 3;
		} else if(x > 90) {
			k = 2;
		} else if(x > 0) {
			k = 1;
		} else if(x <= -270) {
			k = 1;
		} else if(x <= -180) {
			k = 2;
		} else if(x <= -90) {
			k = 3;
		} else if(x <= 0) {
			k = 4;
		}
		return k;
	}
	,vecXDmod: function(vecXD) {
		var sum = 0;
		var _g = 0;
		while(_g < vecXD.length) {
			var i = vecXD[_g];
			++_g;
			sum += i * i;
		}
		return Math.sqrt(sum);
	}
	,vecXDfieldmod: function(vecXDfield) {
		var rez = null;
		var _g = [];
		var _g1 = 0;
		while(_g1 < vecXDfield.length) {
			var i = vecXDfield[_g1];
			++_g1;
			_g.push(this.vecXDmod(i));
		}
		rez = _g;
		return rez;
	}
	,maxabs: function(vecXD) {
		var rez = 0;
		var _g = 0;
		while(_g < vecXD.length) {
			var i = vecXD[_g];
			++_g;
			if(Math.abs(i) > Math.abs(rez)) {
				rez = i;
			}
		}
		return rez;
	}
	,vecXD: function(dot3Da,dot3Db) {
		var rez = null;
		if(!this.vecXDsamesize(dot3Da,dot3Db) || this.vecXDsame(dot3Da,dot3Db)) {
			return rez;
		}
		rez = [];
		var _g1 = 0;
		var _g = dot3Da.length;
		while(_g1 < _g) {
			var i = _g1++;
			rez.push(dot3Db[i] - dot3Da[i]);
		}
		return rez;
	}
	,vecXDone: function(vecXD) {
		var rez = [];
		var lv = this.vecXDmod(vecXD);
		if(lv > 0) {
			var _g = 0;
			while(_g < vecXD.length) {
				var i = vecXD[_g];
				++_g;
				rez.push(i / lv);
			}
			return rez;
		} else {
			rez = vecXD;
		}
		return rez;
	}
	,vecXDfield: function(dots) {
		var rez = [];
		var _g1 = 1;
		var _g = dots.length;
		while(_g1 < _g) {
			var i = _g1++;
			rez.push(this.vecXD(dots[0],dots[i]));
		}
		return rez;
	}
	,vecXDsame: function(vecXDa,vecXDb) {
		if(vecXDa.length == vecXDb.length) {
			var lv = vecXDa.length;
			var _g1 = 0;
			var _g = lv;
			while(_g1 < _g) {
				var i = _g1++;
				if(vecXDa[i] != vecXDb[i]) {
					return false;
				}
			}
			return true;
		}
		return false;
	}
	,vecXDfieldsame: function(vecXDfield) {
		if(this.vecXDfieldsamesize(vecXDfield)) {
			var _g1 = 1;
			var _g = vecXDfield.length;
			while(_g1 < _g) {
				var i = _g1++;
				if(!this.vecXDsame(vecXDfield[0],vecXDfield[i])) {
					return false;
				}
			}
			return true;
		}
		return false;
	}
	,vecXDrandom: function(x) {
		if(x == null) {
			x = 3;
		}
		var _g = [];
		var _g2 = 0;
		var _g1 = x;
		while(_g2 < _g1) {
			var i = _g2++;
			_g.push(0);
		}
		var v0 = _g;
		var _g11 = [];
		var _g3 = 0;
		var _g21 = x;
		while(_g3 < _g21) {
			var i1 = _g3++;
			_g11.push(0);
		}
		var v1 = _g11;
		while(this.vecXDsame(v0,v1)) {
			v1 = [];
			var _g31 = 0;
			var _g22 = x;
			while(_g31 < _g22) {
				var i2 = _g31++;
				v1.push(Math.random() - 0.5);
			}
		}
		v1 = this.vecXDone(v1);
		return v1;
	}
	,vecXDsum: function(vecXDa,vecXDb) {
		return this.sum_xF([vecXDa,vecXDb]);
	}
	,vecXDfieldsum: function(vecXDfield) {
		return this.sum_xF(vecXDfield);
	}
	,vecXDdiff: function(vecXDa,vecXDb) {
		return this.diff_xF([vecXDa,vecXDb]);
	}
	,vecXDfielddiff: function(vecXDfield) {
		return this.diff_xF(vecXDfield);
	}
	,vecXDback: function(vecXD) {
		return this.minus_F(vecXD);
	}
	,vecXDfieldback: function(vecXDfield) {
		var _g = [];
		var _g2 = 0;
		var _g1 = vecXDfield.length;
		while(_g2 < _g1) {
			var i = _g2++;
			_g.push(this.vecXDback(vecXDfield[i]));
		}
		return _g;
	}
	,vecXDparalleled_sameside: function(vecXDa,vecXDb) {
		var rez = null;
		if(vecXDa.length != vecXDb.length) {
			return rez;
		}
		return this.vecXDsame(this.vecXDone(vecXDa),this.vecXDone(vecXDb));
	}
	,vecXDparalleled_opposite: function(vecXDa,vecXDb) {
		var rez = null;
		if(vecXDa.length != vecXDb.length) {
			return rez;
		}
		return this.vecXDparalleled_sameside(vecXDa,this.vecXDback(vecXDb));
	}
	,vecXDparalleled: function(vecXDa,vecXDb) {
		if(!this.vecXDparalleled_sameside(vecXDa,vecXDb)) {
			return this.vecXDparalleled_opposite(vecXDa,vecXDb);
		} else {
			return true;
		}
	}
	,vecXDscalar: function(vecXDa,vecXDb) {
		var rez = null;
		if(vecXDa.length == vecXDb.length) {
			rez = 0;
			var _g1 = 0;
			var _g = vecXDa.length;
			while(_g1 < _g) {
				var i = _g1++;
				rez += vecXDa[i] * vecXDb[i];
			}
		}
		return rez;
	}
	,vecXDcos: function(vecXDa,vecXDb) {
		var rez = null;
		var la = this.vecXDmod(vecXDa);
		var lb = this.vecXDmod(vecXDb);
		if(la > 0 && lb > 0) {
			rez = this.sin_cos_cut(this.vecXDscalar(vecXDa,vecXDb) / (la * lb));
		}
		return rez;
	}
	,vecXDangle: function(vecXDa,vecXDb,rad) {
		if(rad == null) {
			rad = false;
		}
		var rez = null;
		var la = this.vecXDmod(vecXDa);
		var lb = this.vecXDmod(vecXDb);
		if(la > 0 && lb > 0) {
			if(rad) {
				rez = Math.acos(this.vecXDcos(vecXDa,vecXDb));
			} else {
				rez = this.degrees(Math.acos(this.vecXDcos(vecXDa,vecXDb)));
			}
		}
		return rez;
	}
	,vec3Dnormal: function(vec3Da,vec3Db) {
		var rez = null;
		if(vec3Da.length == 3 && vec3Db.length == 3) {
			var a = vec3Da[1] * vec3Db[2] - vec3Da[2] * vec3Db[1];
			var b = -vec3Da[0] * vec3Db[2] + vec3Da[2] * vec3Db[0];
			var c = vec3Da[0] * vec3Db[1] - vec3Da[1] * vec3Db[0];
			return this.vecXDone([a,b,c]);
		}
		return rez;
	}
	,vec3Dfieldnormal: function(vec3Dfield) {
		var rez = null;
		if(vec3Dfield[0].length == 3) {
			var rez1 = vec3Dfield[0];
			var _g1 = 1;
			var _g = vec3Dfield.length;
			while(_g1 < _g) {
				var i = _g1++;
				rez1 = this.vec3Dnormal(rez1,vec3Dfield[i]);
			}
		}
		return rez;
	}
	,vecXDmiddle: function(vecXDa,vecXDb) {
		return this.middle_xF([vecXDa,vecXDb]);
	}
	,vecXDsamesize: function(vecXDa,vecXDb) {
		return vecXDa.length == vecXDb.length;
	}
	,vecXDfieldsamesize: function(vecXDfield) {
		var thesize = vecXDfield[0].length;
		var _g1 = 1;
		var _g = vecXDfield.length;
		while(_g1 < _g) {
			var i = _g1++;
			if(thesize != vecXDfield[i].length) {
				return false;
			}
		}
		return true;
	}
	,vecXDfieldmiddle: function(vecXDfield) {
		return this.middle_xF(vecXDfield);
	}
	,dotXDoffset: function(dotXD,vecXD,t) {
		var rez = null;
		if(t != 0) {
			var lv = vecXD.length;
			if(dotXD.length == lv) {
				rez = [];
				t /= this.vecXDmod(vecXD);
				var _g1 = 0;
				var _g = lv;
				while(_g1 < _g) {
					var i = _g1++;
					rez.push(dotXD[i] + vecXD[i] * t);
				}
			}
			return rez;
		} else {
			return dotXD;
		}
	}
	,dot3Dline3D_x_plane3D: function(dot3D0,vec3D0,vec3Dplane,dplane) {
		if(dplane == null) {
			dplane = 0;
		}
		var rez = null;
		var ldot = dot3D0.length;
		var lvec = vec3D0.length;
		var lplane = vec3Dplane.length;
		if(ldot == 3 && ldot == lvec && lvec == lplane) {
			var checkup = -(vec3Dplane[0] * dot3D0[0] + vec3Dplane[1] * dot3D0[1] + vec3Dplane[2] * dot3D0[2] + dplane);
			var checkdn = vec3Dplane[0] * vec3D0[0] + vec3Dplane[1] * vec3D0[1] + vec3Dplane[2] * vec3D0[2];
			if(checkdn == 0) {
				return rez;
			} else if(checkup == 0) {
				return dot3D0;
			} else {
				var t = checkup / checkdn;
				var _g = [];
				var _g1 = 0;
				while(_g1 < 3) {
					var i = _g1++;
					_g.push(dot3D0[i] + vec3D0[i] * t);
				}
				rez = _g;
			}
		}
		return rez;
	}
	,projection_dot3D_on_plane3D: function(dot3D,plane3D) {
		var rez = null;
		var ldot = dot3D.length;
		var lplane = plane3D.length;
		if(this.vecXDmod(plane3D.slice(0,3)) == 0 || ldot != 3 || lplane != 4) {
			return rez;
		}
		var checkup = -this.multisum_xF([plane3D.slice(0,3),dot3D]) + plane3D[3];
		var checkdn = this.multisum_xF([plane3D.slice(0,3),plane3D.slice(0,3)]);
		if(checkdn == 0) {
			return rez;
		} else if(checkup == 0) {
			return dot3D;
		} else {
			var t = checkup / checkdn;
			var _g = [];
			var _g1 = 0;
			while(_g1 < 3) {
				var i = _g1++;
				_g.push(dot3D[i] + plane3D[i] * t);
			}
			rez = _g;
		}
		return rez;
	}
	,dot3D_to_dot2Dviewplane: function(dot3D,dot3Dox,dot3Doz) {
		var rez = null;
		var t = this.vecXDmod(dot3D);
		var cosox0t = this.multisum_xF([dot3Dox,dot3D]) / (t + this.vecXDmod(dot3Dox));
		var cosoz0t = this.multisum_xF([dot3Doz,dot3D]) / (t + this.vecXDmod(dot3Doz));
		rez = [t * cosox0t,t * cosoz0t];
		return rez;
	}
	,dotXDscale: function(dotXD,scaleXD,dotXDc) {
		var rez = null;
		var _g = [];
		var _g2 = 0;
		var _g1 = dotXD.length;
		while(_g2 < _g1) {
			var i = _g2++;
			_g.push(dotXD[i] * scaleXD[i]);
		}
		var sdot = _g;
		var _g11 = [];
		var _g3 = 0;
		var _g21 = dotXD.length;
		while(_g3 < _g21) {
			var i1 = _g3++;
			_g11.push(dotXDc[i1] * scaleXD[i1]);
		}
		var stc = _g11;
		var vec = this.vecXD(stc,dotXDc);
		rez = this.dotXDoffset(sdot,vec,this.vecXDmod(vec));
		return rez;
	}
	,vec3Drotate: function(vec3D,vec3Daxis,angle,rad) {
		if(rad == null) {
			rad = false;
		}
		var rez = vec3D;
		if(this.vecXDparalleled(vec3D,vec3Daxis) || angle == 0) {
			return rez;
		}
		if(rad) {
			angle = angle;
		} else {
			angle = this.radians(angle);
		}
		var t = [0,0,0];
		var vb = this.vec3Dnormal(vec3Daxis,vec3D);
		var vc = this.vec3Dnormal(vb,vec3Daxis);
		var t0 = this.dotXDoffset(t,vec3Daxis,this.vecXDmod(vec3D) * this.vecXDcos(vec3Daxis,vec3D));
		var t1 = vec3D;
		var v = this.vecXD(t0,t1);
		t1 = this.dotXDoffset(t0,vb,this.vecXDmod(v) * Math.sin(angle));
		t1 = this.dotXDoffset(t1,vc,this.vecXDmod(v) * Math.cos(angle));
		rez = this.vecXD(t,t1);
		return rez;
	}
	,vec3Dfield_rotate_around_vec3Daxes: function(vec3Dfield,vec3Daxes,angles,rad) {
		if(rad == null) {
			rad = false;
		}
		var rez = null;
		if(!this.vecXDfieldsamesize(vec3Dfield) || !this.vecXDfieldsamesize(vec3Daxes) || vec3Dfield[0].length != 3 || vec3Daxes[0].length != 3 || this.zero_inside_F(this.vecXDfieldmod(vec3Dfield)) || this.zero_inside_F(this.vecXDfieldmod(vec3Daxes)) || angles.length != vec3Dfield.length || angles.length != vec3Daxes.length) {
			return rez;
		}
		rez = vec3Dfield;
		var _g1 = 0;
		var _g = angles.length;
		while(_g1 < _g) {
			var i = _g1++;
			var _g3 = 0;
			var _g2 = vec3Dfield.length;
			while(_g3 < _g2) {
				var j = _g3++;
				rez[j] = this.vec3Drotate(rez[j],vec3Daxes[i],angles[i],rad);
			}
		}
		return rez;
	}
	,dot3Drotate: function(dot3D,dot3Dc,vec3D,angle,rad) {
		if(rad == null) {
			rad = false;
		}
		var rez = null;
		if(this.vecXDmod(vec3D) == 0) {
			return rez;
		}
		rez = dot3D;
		if(this.vecXDsame(dot3D,dot3Dc) || angle == 0) {
			return rez;
		}
		var vdot = this.vecXD(dot3Dc,dot3D);
		var d = this.vecXDmod(vdot);
		vdot = this.vec3Drotate(vdot,vec3D,angle,rad);
		rez = this.dotXDoffset(dot3Dc,vdot,d);
		return rez;
	}
	,plane3D_dot3Dnormal: function(dot3D,vec3D) {
		var rez = null;
		if(this.vecXDmod(vec3D) == 0) {
			return rez;
		}
		var d = -this.multisum_xF([vec3D,dot3D]);
		rez = [vec3D[0],vec3D[1],vec3D[2],d];
		return rez;
	}
	,plane3D_dot_vec_vec: function(dot3D,vec3Da,vec3Db) {
		var rez = null;
		if(this.vecXDsame(vec3Da,vec3Db) || this.vecXDmod(vec3Da) == 0 || this.vecXDmod(vec3Db) == 0) {
			return rez;
		}
		rez = this.plane3D_dot3Dnormal(dot3D,this.vec3Dnormal(vec3Da,vec3Db));
		return rez;
	}
	,plane3D_3dots: function(dot3D,dot3Da,dot3Db) {
		var rez = null;
		if(!this.vecXDfieldsamesize([dot3D,dot3Da,dot3Db]) || this.vecXDsame(dot3D,dot3Da) || this.vecXDsame(dot3D,dot3Db) || this.vecXDsame(dot3Da,dot3Db)) {
			return rez;
		}
		rez = this.plane3D_dot_vec_vec(dot3D,this.vecXD(dot3D,dot3Da),this.vecXD(dot3D,dot3Db));
		return rez;
	}
	,plane3D_2dots: function(dot3D,dot3Da) {
		var rez = null;
		if(!this.vecXDsamesize(dot3D,dot3Da) || this.vecXDsame(dot3D,dot3Da)) {
			return rez;
		}
		rez = this.plane3D_dot3Dnormal(dot3D,this.vecXD(dot3D,dot3Da));
		return rez;
	}
	,distance_dot3D_plane3D: function(dot3D,plane3D) {
		var rez = null;
		if(this.vecXDmod(plane3D.slice(0,3)) == 0) {
			return rez;
		}
		rez = Math.abs(this.multisum_xF([plane3D.slice(0,3),dot3D]) + plane3D[3]) / this.vecXDmod(plane3D.slice(0,3));
		return rez;
	}
	,random_vec3D_in_plane3D: function(plane3D) {
		var rez = null;
		if(this.vecXDmod(plane3D.slice(0,3)) == 0) {
			return rez;
		}
		var t0 = this.vecXDrandom(3);
		t0 = this.projection_dot3D_on_plane3D(t0,plane3D);
		var t1 = t0;
		while(this.vecXDsame(t0,t1)) {
			t1 = [];
			var _g = 0;
			while(_g < 3) {
				var i = _g++;
				t1.push(t0[i] + Math.random() - 0.5);
			}
			t1 = this.projection_dot3D_on_plane3D(t1,plane3D);
		}
		rez = this.vecXD(t0,t1);
		return rez;
	}
	,random_dot3D_in_plane3D: function(plane3D,dot3D,radius) {
		var rez = null;
		if(plane3D.length != 4 || this.vecXDmod(plane3D.slice(0,3)) == 0) {
			return rez;
		}
		rez = dot3D;
		if(radius == 0) {
			return rez;
		}
		var vec3D = this.random_vec3D_in_plane3D(plane3D);
		rez = this.dotXDoffset(dot3D,vec3D,radius * Math.random());
		return rez;
	}
	,curve3Dbeziercubic: function(dot3D1,vec3D1,distance1,dot3D2,vec3D2,distance2) {
		var rez = null;
		if(!this.vecXDfieldsamesize([dot3D1,vec3D1,dot3D2,vec3D2]) || dot3D1.length != 3) {
			return rez;
		}
		var r1 = this.dotXDoffset(dot3D1,vec3D1,distance1);
		var r2 = this.dotXDoffset(dot3D2,vec3D2,distance2);
		rez = [dot3D1,r1,r2,dot3D2];
		return rez;
	}
	,curve3Dbeziercubic_3dots: function(dot3D0,dot3D1,dot3D2,lever1,lever2,a_s) {
		if(a_s == null) {
			a_s = -1;
		}
		if(lever2 == null) {
			lever2 = 0.55;
		}
		if(lever1 == null) {
			lever1 = 0.55;
		}
		var rez = null;
		if(!this.vecXDfieldsamesize([dot3D0,dot3D1,dot3D2]) || dot3D0.length != 3) {
			return rez;
		}
		var v1 = this.vecXD(dot3D0,dot3D1);
		var v2 = this.vecXD(dot3D0,dot3D2);
		var v12 = this.vecXD(dot3D1,dot3D2);
		var t = this.dotXDoffset(dot3D1,v12,this.vecXDmod(v12) / 2);
		var v = this.vecXD(dot3D0,t);
		var r1 = null;
		var r2 = null;
		if(a_s < 0) {
			if(lever1 > 0) {
				r1 = this.dotXDoffset(dot3D1,v2,this.vecXDmod(v2) * lever1);
			} else if(lever1 < 0) {
				r1 = this.dotXDoffset(dot3D1,v1,this.vecXDmod(v1) * lever1);
			} else {
				r1 = dot3D1;
			}
			if(lever2 > 0) {
				r2 = this.dotXDoffset(dot3D2,v1,this.vecXDmod(v1) * lever2);
			} else if(lever2 < 0) {
				r2 = this.dotXDoffset(dot3D2,v2,this.vecXDmod(v2) * lever2);
			} else {
				r2 = dot3D2;
			}
		} else if(a_s > 0) {
			if(lever1 > 0) {
				r1 = this.dotXDoffset(dot3D1,v1,this.vecXDmod(v2) * lever1);
			} else if(lever1 < 0) {
				r1 = this.dotXDoffset(dot3D1,v2,this.vecXDmod(v1) * lever1);
			} else {
				r1 = dot3D1;
			}
			if(lever2 > 0) {
				r2 = this.dotXDoffset(dot3D2,v2,this.vecXDmod(v1) * lever2);
			} else if(lever2 < 0) {
				r2 = this.dotXDoffset(dot3D2,v1,this.vecXDmod(v2) * lever2);
			} else {
				r2 = dot3D2;
			}
		} else {
			r1 = this.dotXDoffset(dot3D1,v,this.vecXDmod(v) * lever1);
			r2 = this.dotXDoffset(dot3D2,v,this.vecXDmod(v) * lever2);
		}
		rez = [dot3D1,r1,r2,dot3D2];
		return rez;
	}
	,line3Dbeziercubic_2dots: function(dot3D0,dot3D1) {
		var rez = null;
		if(!this.vecXDsamesize(dot3D0,dot3D1) || dot3D0.length != 3) {
			return rez;
		}
		var v = this.vecXD(dot3D0,dot3D1);
		var lv = this.vecXDmod(v);
		var lever0 = this.dotXDoffset(dot3D0,v,lv / 3);
		var lever1 = this.dotXDoffset(dot3D0,v,lv * 2 / 3);
		rez = [dot3D0,lever0,lever1,dot3D1];
		return rez;
	}
	,line3Dbeziercubic: function(dot3D,vec3D,distance) {
		var rez = null;
		if(distance == 0 || !this.vecXDsamesize(dot3D,vec3D) || dot3D.length != 3 || this.vecXDmod(vec3D) == 0) {
			return rez;
		}
		rez = this.line3Dbeziercubic_2dots(dot3D,this.dotXDoffset(dot3D,vec3D,distance));
		return rez;
	}
	,beziercubic3D_4to12: function(curve) {
		var rez = null;
		if(curve.length == 4 && curve[0].length == 3 && this.vecXDfieldsamesize(curve)) {
			var _g = [];
			var _g1 = 0;
			while(_g1 < 4) {
				var i = _g1++;
				var _g2 = 0;
				while(_g2 < 3) {
					var ai = _g2++;
					_g.push(curve[i][ai]);
				}
			}
			rez = _g;
		}
		return rez;
	}
	,beziercubic3D_12to4: function(curve) {
		var rez = null;
		if(curve.length == 12) {
			var _g = [];
			var _g1 = 0;
			var _g2 = [0,3,6,9];
			while(_g1 < _g2.length) {
				var i = _g2[_g1];
				++_g1;
				var _g3 = [];
				var _g4 = 0;
				while(_g4 < 3) {
					var ai = _g4++;
					_g3.push(curve[ai + i]);
				}
				_g.push(_g3);
			}
			rez = _g;
		}
		return rez;
	}
	,beziercubic3D_derivativeparameters: function(curve) {
		var rez = null;
		var cl = curve.length;
		if(cl == 4 && curve[0].length == 3 && this.vecXDfieldsamesize(curve)) {
			var _g = [];
			var _g1 = 0;
			while(_g1 < 3) {
				var i = _g1++;
				var _g2 = [];
				var _g3 = 0;
				while(_g3 < 4) {
					var p = _g3++;
					_g2.push(curve[p][i]);
				}
				_g.push(_g2);
			}
			rez = _g;
		}
		return rez;
	}
	,beziercubic_derivative: function(bcp,p) {
		var rez = null;
		if(bcp.length == 4) {
			rez = 3 * (1 - p) * (1 - p) * (bcp[1] - bcp[0]) + 6 * (1 - p) * p * (bcp[2] - bcp[1]) + 3 * p * p * (bcp[3] - bcp[2]);
		}
		return rez;
	}
	,beziercubic3D_derivative: function(curve,p) {
		var rez = null;
		if(curve.length == 4 && curve[0].length == 3 && this.vecXDfieldsamesize(curve)) {
			var _g = [];
			var _g1 = 0;
			var _g2 = this.beziercubic3D_derivativeparameters(curve);
			while(_g1 < _g2.length) {
				var i = _g2[_g1];
				++_g1;
				_g.push(this.beziercubic_derivative(i,p));
			}
			rez = _g;
		}
		return rez;
	}
	,beziercubic_support_dot_one: function(beziercubic_one_axis_coordinates) {
		var c = beziercubic_one_axis_coordinates;
		var rez = null;
		if(c.length != 4) {
			return rez;
		}
		return (-5 * c[0] + 18 * c[1] - 9 * c[2] + 2 * c[3]) / 6;
	}
	,beziercubic3D_support_dot_one: function(curve3D_4dots) {
		var rez = null;
		var c = curve3D_4dots;
		if(c.length != 4 || !this.vecXDfieldsamesize(c)) {
			return rez;
		}
		var _g = [];
		var _g1 = 0;
		var _g2 = this.beziercubic3D_derivativeparameters(c);
		while(_g1 < _g2.length) {
			var i = _g2[_g1];
			++_g1;
			_g.push(this.beziercubic_support_dot_one(i));
		}
		rez = _g;
		return rez;
	}
	,beziercubic_support_dot_two: function(beziercubic_one_axis_coordinates) {
		var c = beziercubic_one_axis_coordinates;
		var rez = null;
		if(c.length != 4) {
			return rez;
		}
		return (2 * c[0] - 9 * c[1] + 18 * c[2] - 5 * c[3]) / 6;
	}
	,beziercubic3D_support_dot_two: function(curve3D_4dots) {
		var rez = null;
		var c = curve3D_4dots;
		if(c.length != 4 || !this.vecXDfieldsamesize(c)) {
			return rez;
		}
		var _g = [];
		var _g1 = 0;
		var _g2 = this.beziercubic3D_derivativeparameters(c);
		while(_g1 < _g2.length) {
			var i = _g2[_g1];
			++_g1;
			_g.push(this.beziercubic_support_dot_two(i));
		}
		rez = _g;
		return rez;
	}
	,beziercubic3D_follow_4dots_trajectory: function(dots) {
		var rez = null;
		if(dots.length != 4 || !this.vecXDfieldsamesize(dots)) {
			return rez;
		}
		var dot_one = this.beziercubic3D_support_dot_one(dots);
		var dot_two = this.beziercubic3D_support_dot_two(dots);
		rez = [dots[0],dot_one,dot_two,dots[3]];
		return rez;
	}
	,beziercubic_coordinate: function(beziercubic_one_axis_coordinates,parameter) {
		var rez = null;
		var c = beziercubic_one_axis_coordinates;
		var p = parameter;
		if(c.length != 4) {
			return rez;
		}
		rez = (1 - p) * (1 - p) * (1 - p) * c[0] + 3 * (1 - p) * (1 - p) * p * c[1] + 3 * (1 - p) * p * p * c[2] + p * p * p * c[3];
		return rez;
	}
	,beziercubic3Ddot: function(beziercubic3D,parameter) {
		var rez = null;
		var c = beziercubic3D;
		var p = parameter;
		if(c.length != 4 || c[0].length != 3 || !this.vecXDfieldsamesize(c)) {
			return rez;
		}
		var _g = [];
		var _g1 = 0;
		var _g2 = this.beziercubic3D_derivativeparameters(c);
		while(_g1 < _g2.length) {
			var i = _g2[_g1];
			++_g1;
			_g.push(this.beziercubic_coordinate(i,p));
		}
		rez = _g;
		return rez;
	}
	,curve3D_4dots_follow_beziercubic_trajectory: function(beziercubic3D) {
		var rez = null;
		var c = beziercubic3D;
		if(c.length != 4 || !this.vecXDfieldsamesize(c)) {
			return rez;
		}
		c[1] = this.beziercubic3Ddot(c,0.333333333333333315);
		c[2] = this.beziercubic3Ddot(c,0.66666666666666663);
		return c;
	}
	,curve3Doffset: function(curve3D,vec3D,distance) {
		var rez = null;
		if(curve3D.length != 4 || curve3D[0].length != 3 || !this.vecXDfieldsamesize(curve3D) || vec3D.length != 3) {
			return rez;
		}
		var _g = [];
		var _g1 = 0;
		while(_g1 < curve3D.length) {
			var i = curve3D[_g1];
			++_g1;
			_g.push(this.dotXDoffset(i,vec3D,distance));
		}
		return _g;
	}
	,curve3Drotate: function(curve3D,dot3D,vec3D,angle,rad) {
		if(rad == null) {
			rad = false;
		}
		var rez = null;
		if(curve3D.length != 4 || curve3D[0].length != 3 || !this.vecXDfieldsamesize(curve3D) || dot3D.length != 3 || vec3D.length != 3 || this.vecXDmod(vec3D) == 0) {
			return rez;
		}
		if(angle == 0) {
			return curve3D;
		}
		var _g = [];
		var _g1 = 0;
		while(_g1 < curve3D.length) {
			var i = curve3D[_g1];
			++_g1;
			_g.push(this.dot3Drotate(i,dot3D,vec3D,angle,rad));
		}
		return _g;
	}
	,curve3Dscale: function(curve3D,scale_xyz,dot3D) {
		var rez = null;
		if(curve3D.length != 4 || curve3D[0].length != 3 || !this.vecXDfieldsamesize(curve3D) || dot3D.length != 3 || scale_xyz.length != 3) {
			return rez;
		}
		if(this.vecXDmod(scale_xyz) == 0) {
			var _g = [];
			var _g1 = 0;
			while(_g1 < 4) {
				var i = _g1++;
				_g.push([0,0,0]);
			}
			return _g;
		}
		var _g2 = [];
		var _g11 = 0;
		while(_g11 < curve3D.length) {
			var i1 = curve3D[_g11];
			++_g11;
			_g2.push(this.dotXDscale(i1,scale_xyz,dot3D));
		}
		return _g2;
	}
	,ellipse2Dperimeter_ramanujan: function(semiaxis_a,semiaxis_b) {
		var rez = null;
		var a = semiaxis_a;
		var b = semiaxis_b;
		if(a < 0 || b < 0) {
			return rez;
		}
		var l1 = Math.PI * (3 * (a + b) - Math.sqrt((3 * a + b) * (a + 3 * b)));
		var l2 = Math.PI * (a + b) * (1 + 3 * (a - b) * (a - b) / (a + b) / (a + b) / (10 + Math.sqrt(4 - 3 * (a - b) * (a - b) / (a + b) / (a + b))));
		rez = Math.max(l1,l2);
		return rez;
	}
	,tangent_centered_ellipse2Ddot: function(semiaxis_a,semiaxis_b,ellipse_dot2D) {
		var rez = null;
		var a = semiaxis_a;
		var b = semiaxis_b;
		var x0 = ellipse_dot2D[0];
		var y0 = ellipse_dot2D[1];
		var x;
		var y;
		var v = null;
		if(x0 != 0) {
			x = 0.9 * x0;
			if(x0 > 0) {
				if(y0 == 0) {
					v = [[x0,y0],[x0,1]];
				} else {
					y = (1 - x * x0 / (a * a)) * b * b / y0;
					if(y0 > 0) {
						v = [[x0,y0],[x,y]];
					} else {
						v = [[x,y],[x0,y0]];
					}
				}
			} else if(x0 < 0) {
				if(y0 == 0) {
					v = [[x0,y0],[x0,-1]];
				} else {
					y = (1 - x * x0 / (a * a)) * b * b / y0;
					if(y0 > 0) {
						v = [[x,y],[x0,y0]];
					} else {
						v = [[x0,y0],[x,y]];
					}
				}
			}
		} else {
			y = 0.9 * y0;
			if(y0 > 0) {
				if(x0 == 0) {
					v = [[x0,y0],[-1,y0]];
				} else {
					x = (1 - y * y0 / (b * b)) * a * a / x0;
					if(x0 > 0) {
						v = [[x,y],[x0,y0]];
					} else {
						v = [[x0,y0],[x,y]];
					}
				}
			} else if(y0 < 0) {
				if(x0 == 0) {
					v = [[x0,y0],[1,y0]];
				} else {
					x = (1 - y * y0 / (b * b)) * a * a / x0;
					if(x0 < 0) {
						v = [[x,y],[x0,y0]];
					} else {
						v = [[x0,y0],[x,y]];
					}
				}
			}
		}
		return v;
	}
	,ellipse_e_parameter: function(semiaxis_a,semiaxis_b) {
		var rez = null;
		var a = semiaxis_a;
		var b = semiaxis_b;
		if(a < 0 || b < 0 || a <= 0 && b <= 0) {
			return rez;
		}
		if(a >= b) {
			rez = Math.sqrt(1 - b * b / (a * a));
		} else {
			rez = -Math.sqrt(1 - a * a / (b * b));
		}
		return rez;
	}
	,ellipse_c_parameter: function(semiaxis_a,semiaxis_b) {
		var rez = null;
		var a = semiaxis_a;
		var b = semiaxis_b;
		var e = this.ellipse_e_parameter(a,b);
		if(e == null) {
			return rez;
		}
		if(a >= b) {
			rez = a * e;
		} else {
			rez = b * e;
		}
		return rez;
	}
	,tangent_vec3D_in_plane_of_ellipse2D_placed_in_3Dspace: function(dot3D,vec3Dnormal_ellipse_plane,vec3Dsemiaxis_a_direction,semiaxis_a,semiaxis_b,semiaxis_a_negative,semiaxis_b_negative,angle,rad) {
		var rez = null;
		var t = dot3D;
		var vn = vec3Dnormal_ellipse_plane;
		var va = vec3Dsemiaxis_a_direction;
		var a = semiaxis_a;
		var b = semiaxis_b;
		var an = semiaxis_a_negative;
		var bn = semiaxis_b_negative;
		var ea = null;
		var eb = null;
		var _g = this.angle_quadrant(angle,rad);
		switch(_g) {
		case 1:
			ea = a;
			eb = b;
			break;
		case 2:
			ea = an;
			eb = b;
			break;
		case 3:
			ea = an;
			eb = bn;
			break;
		case 4:
			ea = a;
			eb = bn;
			break;
		}
		var ep = this.plane3D_dot3Dnormal(t,vn);
		var va1 = this.projection_vec3D_on_plane3D(va,ep);
		var vb = this.vec3Dnormal(vn,va1);
		var edot = this.ellipse2Ddot(angle,ea,eb,rad);
		var dxy0dxy1 = this.tangent_centered_ellipse2Ddot(ea,eb,edot);
		var te = this.dotXDoffset(t,va1,dxy0dxy1[0][0]);
		var te1 = this.dotXDoffset(te,vb,dxy0dxy1[0][1]);
		var tt = this.dotXDoffset(t,va1,dxy0dxy1[1][0]);
		var tt1 = this.dotXDoffset(tt,vb,dxy0dxy1[1][1]);
		rez = this.vecXD(te1,tt1);
		return rez;
	}
	,ellipse3D_dots: function(dot3D,vec3Dsemiaxes,semiaxes) {
		var rez = null;
		if(dot3D.length != 3 || vec3Dsemiaxes.length != 4 || !this.vecXDfieldsamesize(vec3Dsemiaxes) || semiaxes.length != 4) {
			return rez;
		}
		var t0 = dot3D;
		var va = vec3Dsemiaxes[0];
		var vb = vec3Dsemiaxes[1];
		var vad = vec3Dsemiaxes[2];
		var vbd = vec3Dsemiaxes[3];
		var a = semiaxes[0];
		var b = semiaxes[1];
		var ad = semiaxes[2];
		var bd = semiaxes[3];
		var cos45 = Math.cos(this.radians(45));
		var v = [va,vb,vad,vbd];
		var d = [a * cos45,b * cos45,ad * cos45,bd * cos45];
		var vv = [vb,vad,vbd,va];
		var dd = [b * cos45,ad * cos45,bd * cos45,a * cos45];
		rez = [t0];
		var _g = 0;
		while(_g < 4) {
			var i = _g++;
			rez.push(this.dotXDoffset(t0,vec3Dsemiaxes[i],semiaxes[i]));
			rez.push(this.dotXDoffset(this.dotXDoffset(t0,v[i],d[i]),vv[i],dd[i]));
		}
		return rez;
	}
	,ellipse2Ddot: function(angle,semiaxis_a_ox,semiaxis_b_oy,rad) {
		if(rad == null) {
			rad = false;
		}
		var u = angle;
		var a = semiaxis_a_ox;
		var b = semiaxis_b_oy;
		if(!rad) {
			a = this.radians(a);
		}
		return [a * Math.cos(u),b * Math.sin(u)];
	}
	,curve2D_4dots_elliptic_shape_restricted_to_quarter: function(angle0,angle1,semiaxis_a_ox,semiaxis_b_oy,rad) {
		if(rad == null) {
			rad = false;
		}
		var rez = null;
		var a0 = rad ? this.degrees(angle0) : angle0;
		var a1 = rad ? this.degrees(angle1) : angle1;
		if(a0 > 90) {
			a0 = 90;
		} else if(a0 < 0) {
			a0 = 0;
		} else {
			a0 = a0;
		}
		if(a1 > 90) {
			a1 = 90;
		} else if(a1 < 0) {
			a1 = 0;
		} else {
			a1 = a1;
		}
		if(a0 >= a1) {
			a0 = 0;
		} else {
			a0 = a0;
		}
		var du = a1 - a0;
		var ae = semiaxis_a_ox;
		var be = semiaxis_b_oy;
		var _g = [];
		var _g1 = 0;
		var _g2 = [a0,a0 + du / 3,a0 + du * 2 / 3,a0 + du];
		while(_g1 < _g2.length) {
			var a = _g2[_g1];
			++_g1;
			_g.push(this.ellipse2Ddot(a,ae,be,rad));
		}
		rez = _g;
		return rez;
	}
	,beziercubic3D_elliptic_shape_restricted_to_quarter: function(dot3Dc,vec3D_a_ox,vec3D_b_ox,semiaxis_a_ox,semiaxis_b_oy,angle0,angle1,rad) {
		if(rad == null) {
			rad = false;
		}
		var rez = null;
		var tc = dot3Dc;
		var va = vec3D_a_ox;
		var vb = vec3D_b_ox;
		var a = semiaxis_a_ox;
		var b = semiaxis_b_oy;
		var dxdy = this.curve2D_4dots_elliptic_shape_restricted_to_quarter(angle0,angle1,a,b,rad);
		var _g = [];
		var _g1 = 0;
		while(_g1 < dxdy.length) {
			var i = dxdy[_g1];
			++_g1;
			_g.push(this.dotXDoffset(this.dotXDoffset(tc,va,i[0]),vb,i[1]));
		}
		rez = _g;
		rez = this.beziercubic3D_follow_4dots_trajectory(rez);
		return rez;
	}
	,angle_required_to_place_curve_on_ellipse: function(curve_length,semiaxis_a_ox,semiaxis_b_oy,angle0,rad) {
		if(rad == null) {
			rad = false;
		}
		var rez = null;
		var cl = curve_length;
		var a = semiaxis_a_ox;
		var b = semiaxis_b_oy;
		var u = angle0;
		var le = 0;
		var xy = null;
		if(cl > 0 && a > 0 && b > 0) {
			var xy0 = this.ellipse2Ddot(u,a,b,rad);
			if(rad) {
				u = this.degrees(u);
			}
			var _g = 1;
			while(_g < 361) {
				var ue = _g++;
				xy = this.ellipse2Ddot(u + ue,a,b);
				le += this.vecXDmod(this.vecXD(xy0,xy));
				if(le >= cl) {
					if(rad) {
						return this.radians(ue);
					} else {
						return ue;
					}
				}
				xy0 = xy;
			}
			if(rad) {
				rez = this.radians(360);
			} else {
				rez = 360;
			}
		}
		return rez;
	}
	,polygon3D_inside_ellipse: function(dot3D,vec3Dsemiaxes,semiaxes,angle_proportions) {
		var rez = null;
		if(dot3D.length != 3 || vec3Dsemiaxes.length != 4 || !this.vecXDfieldsamesize(vec3Dsemiaxes) || semiaxes.length != 4 || angle_proportions.length < 1 || this.negative_inside_F(angle_proportions) || this.sum_F(angle_proportions) == 0) {
			return rez;
		}
		var t0 = dot3D;
		var va = vec3Dsemiaxes[0];
		var vb = vec3Dsemiaxes[1];
		var vad = vec3Dsemiaxes[2];
		var vbd = vec3Dsemiaxes[3];
		var a = semiaxes[0];
		var b = semiaxes[1];
		var ad = semiaxes[2];
		var bd = semiaxes[3];
		var doli = angle_proportions;
		var u = 0;
		var x = 360 / this.sum_F(doli);
		var axis_a;
		var axis_b;
		var dlina_a;
		var dlina_b;
		var v;
		var d;
		var vv;
		var dd;
		rez = [t0];
		var _g = 0;
		while(_g < doli.length) {
			var i = doli[_g];
			++_g;
			axis_a = va;
			dlina_a = a;
			axis_b = vb;
			dlina_b = b;
			u += i * x;
			if(u > 90 && u <= 270) {
				axis_a = vad;
				dlina_a = ad;
			}
			if(u > 180) {
				axis_b = vbd;
				dlina_b = bd;
			}
			v = axis_a;
			d = dlina_a * Math.abs(Math.cos(this.radians(u)));
			vv = axis_b;
			dd = dlina_b * Math.abs(Math.sin(this.radians(u)));
			rez.push(this.dotXDoffset(this.dotXDoffset(t0,v,d),vv,dd));
		}
		return rez;
	}
	,polygon3D_vec3Dfield_distance: function(dot3D,vec3Dfield,distances) {
		var rez = null;
		if(dot3D.length != 3 || !this.vecXDfieldsamesize(vec3Dfield) || vec3Dfield.length != distances.length || vec3Dfield[0].length != 3) {
			return rez;
		}
		rez = [dot3D];
		var _g1 = 0;
		var _g = vec3Dfield.length;
		while(_g1 < _g) {
			var i = _g1++;
			rez.push(this.dotXDoffset(dot3D,vec3Dfield[i],distances[i]));
		}
		return rez;
	}
	,polygon3D_in_plane: function(dot3D,vec3Dplane_normal,vec3Dsemiaxis_a_direction,angle_proportions,distances) {
		var rez = null;
		var t = dot3D;
		var vn = vec3Dplane_normal;
		var va = vec3Dsemiaxis_a_direction;
		var ap = angle_proportions;
		var d = distances;
		if(t.length != 3 || vn.length != 3 || va.length != 3 || ap.length != d.length || this.vecXDparalleled(va,vn)) {
			return rez;
		}
		var x = 360 / this.sum_F(ap);
		va = this.projection_vec3D_on_plane3D(va,[vn[0],vn[1],vn[2],0]);
		rez = [t];
		var _g1 = 0;
		var _g = d.length;
		while(_g1 < _g) {
			var i = _g1++;
			rez.push(this.dotXDoffset(t,this.vec3Drotate(va,vn,x * ap[i]),distances[i]));
		}
		return rez;
	}
	,polygon3D_to_vec3Dfield: function(polygon3D) {
		var _g = [];
		var _g2 = 1;
		var _g1 = polygon3D.length;
		while(_g2 < _g1) {
			var i = _g2++;
			_g.push(this.vecXD(polygon3D[0],polygon3D[i]));
		}
		return _g;
	}
	,projection_vec3D_on_plane3D: function(vec3D,plane3D) {
		var rez = null;
		if(vec3D.length != 3 || plane3D.length != 4) {
			return rez;
		}
		var _g = [];
		var _g1 = 0;
		while(_g1 < 3) {
			var i = _g1++;
			_g.push(plane3D[i]);
		}
		var vp = _g;
		if(this.vecXDparalleled(vec3D,vp) || this.vecXDmod(vec3D) == 0 || this.vecXDmod(vp) == 0) {
			return rez;
		}
		rez = vec3D;
		var t0 = [0,0,0];
		var t1 = this.dotXDoffset(t0,vec3D,1);
		t1 = this.projection_dot3D_on_plane3D(t1,plane3D);
		rez = this.vecXD(t0,t1);
		return rez;
	}
	,angle_vec3Dvec3D_projection_on_plane3D: function(vec3D1,vec3D2,plane3D,rad) {
		if(rad == null) {
			rad = false;
		}
		var rez = null;
		var v1 = vec3D1;
		var v2 = vec3D2;
		var v1l = v1.length;
		var v2l = v2.length;
		var v1mod = this.vecXDmod(v1);
		var v2mod = this.vecXDmod(v2);
		if(v1l != 3 || v2l != 3 || v1mod == 0 || v2mod == 0) {
			return rez;
		}
		var p = plane3D;
		if(p.length < 3) {
			return rez;
		}
		var _g = [];
		var _g1 = 0;
		while(_g1 < 3) {
			var i = _g1++;
			_g.push(p[i]);
		}
		var vn = _g;
		if(this.vecXDmod(vn) == 0) {
			return rez;
		}
		rez = 0;
		if(this.vecXDparalleled_sameside(v1,v2)) {
			return rez;
		}
		var pv1 = this.projection_vec3D_on_plane3D(v1,vn);
		var pv2 = this.projection_vec3D_on_plane3D(v2,vn);
		var pvn = this.vecXDparalleled(pv1,pv2) ? vn : this.vec3Dnormal(pv1,pv2);
		var uvnpvn = this.vecXDangle(vn,pvn,rad);
		var uvv = this.vecXDangle(v1,v2,rad);
		var uznak = rad ? this.radians(90) : 90;
		if(uvnpvn > uznak) {
			rez = -uvv;
		} else {
			rez = uvv;
		}
		return rez;
	}
};
var HxOverrides = function() { };
HxOverrides.__name__ = true;
HxOverrides.cca = function(s,index) {
	var x = s.charCodeAt(index);
	if(x != x) {
		return undefined;
	}
	return x;
};
Math.__name__ = true;
var Std = function() { };
Std.__name__ = true;
Std.string = function(s) {
	return js_Boot.__string_rec(s,"");
};
Std.parseInt = function(x) {
	var v = parseInt(x,10);
	if(v == 0 && (HxOverrides.cca(x,1) == 120 || HxOverrides.cca(x,1) == 88)) {
		v = parseInt(x);
	}
	if(isNaN(v)) {
		return null;
	}
	return v;
};
var js_Boot = function() { };
js_Boot.__name__ = true;
js_Boot.__string_rec = function(o,s) {
	if(o == null) {
		return "null";
	}
	if(s.length >= 5) {
		return "<...>";
	}
	var t = typeof(o);
	if(t == "function" && (o.__name__ || o.__ename__)) {
		t = "object";
	}
	switch(t) {
	case "function":
		return "<function>";
	case "object":
		if(o instanceof Array) {
			if(o.__enum__) {
				if(o.length == 2) {
					return o[0];
				}
				var str = o[0] + "(";
				s += "\t";
				var _g1 = 2;
				var _g = o.length;
				while(_g1 < _g) {
					var i = _g1++;
					if(i != 2) {
						str += "," + js_Boot.__string_rec(o[i],s);
					} else {
						str += js_Boot.__string_rec(o[i],s);
					}
				}
				return str + ")";
			}
			var l = o.length;
			var i1;
			var str1 = "[";
			s += "\t";
			var _g11 = 0;
			var _g2 = l;
			while(_g11 < _g2) {
				var i2 = _g11++;
				str1 += (i2 > 0 ? "," : "") + js_Boot.__string_rec(o[i2],s);
			}
			str1 += "]";
			return str1;
		}
		var tostr;
		try {
			tostr = o.toString;
		} catch( e ) {
			return "???";
		}
		if(tostr != null && tostr != Object.toString && typeof(tostr) == "function") {
			var s2 = o.toString();
			if(s2 != "[object Object]") {
				return s2;
			}
		}
		var k = null;
		var str2 = "{\n";
		s += "\t";
		var hasp = o.hasOwnProperty != null;
		for( var k in o ) {
		if(hasp && !o.hasOwnProperty(k)) {
			continue;
		}
		if(k == "prototype" || k == "__class__" || k == "__super__" || k == "__interfaces__" || k == "__properties__") {
			continue;
		}
		if(str2.length != 2) {
			str2 += ", \n";
		}
		str2 += s + k + " : " + js_Boot.__string_rec(o[k],s);
		}
		s = s.substring(1);
		str2 += "\n" + s + "}";
		return str2;
	case "string":
		return o;
	default:
		return String(o);
	}
};
String.__name__ = true;
Array.__name__ = true;
GeometryXD.main();
})(typeof exports != "undefined" ? exports : typeof window != "undefined" ? window : typeof self != "undefined" ? self : this);
