Attribute VB_Name = "Sub_VXOD_GLA"
Sub VXOD_GLA()

DOROGA=int(val(DOCELL_GLA.Cells(1,2).value))
NEROVNO=int(val(DOCELL_GLA.Cells(2,2).value))
n_ko=int(val(DOCELL_GLA.Cells(3,2).value))
KORPUS=int(val(DOCELL_GLA.Cells(4,2).value))
del_X_rul=val(DOCELL_GLA.Cells(5,2).value)
ugol_ko_max=val(DOCELL_GLA.Cells(9,2).value)
KAK_POEDEM=int(val(DOCELL_GLA.Cells(14,2).value))
POEDEM_DO=val(DOCELL_GLA.Cells(15,2).value)
EDEM_KUSOK=int(val(DOCELL_GLA.Cells(16,2).value))
KUSOK_OT=val(DOCELL_GLA.Cells(17,2).value)
KUSOK_DO=val(DOCELL_GLA.Cells(18,2).value)
IDUET_VETER=int(val(DOCELL_GLA.Cells(19,2).value))
VETER=val(DOCELL_GLA.Cells(20,2).value)
IDUET_REZKO=int(val(DOCELL_GLA.Cells(21,2).value))
REZKO_OT=val(DOCELL_GLA.Cells(22,2).value)
REZKO_DO=val(DOCELL_GLA.Cells(23,2).value)
UGOL_VETRA=val(DOCELL_GLA.Cells(24,2).value)
MAX_SKOR_YES=int(val(DOCELL_GLA.Cells(25,2).value))
MAX_SKOR=val(DOCELL_GLA.Cells(26,2).value)
START_SKOR_YES=int(val(DOCELL_GLA.Cells(27,2).value))
START_SKOR=val(DOCELL_GLA.Cells(28,2).value)
del_Y_kurs=val(DOCELL_GLA.Cells(15,1).value)

END SUB
