Attribute VB_Name = "Sub_VXOD_KOR"
Sub VXOD_KOR()

global NOMER_KOR=VAL(DOCELL_KOR.CELLS(int(VAL(DOCELL_GLA.CELLS(4,2).VALUE)),1).VALUE)
global OPIS_KOR=DOCELL_KOR.CELLS(int(VAL(DOCELL_GLA.CELLS(4,2).VALUE)),2).VALUE
global D_down=VAL(DOCELL_KOR.CELLS(int(VAL(DOCELL_GLA.CELLS(4,2).VALUE)),3).VALUE)
global D_up=VAL(DOCELL_KOR.CELLS(int(VAL(DOCELL_GLA.CELLS(4,2).VALUE)),4).VALUE)
global D_right=VAL(DOCELL_KOR.CELLS(int(VAL(DOCELL_GLA.CELLS(4,2).VALUE)),5).VALUE)
global D_left=VAL(DOCELL_KOR.CELLS(int(VAL(DOCELL_GLA.CELLS(4,2).VALUE)),6).VALUE)
global D_back=VAL(DOCELL_KOR.CELLS(int(VAL(DOCELL_GLA.CELLS(4,2).VALUE)),7).VALUE)
global D_front=VAL(DOCELL_KOR.CELLS(int(VAL(DOCELL_GLA.CELLS(4,2).VALUE)),8).VALUE)
global m_korp=VAL(DOCELL_KOR.CELLS(int(VAL(DOCELL_GLA.CELLS(4,2).VALUE)),9).VALUE)
global J_vert=VAL(DOCELL_KOR.CELLS(int(VAL(DOCELL_GLA.CELLS(4,2).VALUE)),10).VALUE)
global J_pop=VAL(DOCELL_KOR.CELLS(int(VAL(DOCELL_GLA.CELLS(4,2).VALUE)),11).VALUE)
global J_prod=VAL(DOCELL_KOR.CELLS(int(VAL(DOCELL_GLA.CELLS(4,2).VALUE)),12).VALUE)
global Cx_down=VAL(DOCELL_KOR.CELLS(int(VAL(DOCELL_GLA.CELLS(4,2).VALUE)),13).VALUE)
global Cx_up=VAL(DOCELL_KOR.CELLS(int(VAL(DOCELL_GLA.CELLS(4,2).VALUE)),14).VALUE)
global Cx_right=VAL(DOCELL_KOR.CELLS(int(VAL(DOCELL_GLA.CELLS(4,2).VALUE)),15).VALUE)
global Cx_left=VAL(DOCELL_KOR.CELLS(int(VAL(DOCELL_GLA.CELLS(4,2).VALUE)),16).VALUE)
global Cx_back=VAL(DOCELL_KOR.CELLS(int(VAL(DOCELL_GLA.CELLS(4,2).VALUE)),17).VALUE)
global Cx_front=VAL(DOCELL_KOR.CELLS(int(VAL(DOCELL_GLA.CELLS(4,2).VALUE)),18).VALUE)
global NAME_GIF=DOCELL_KOR.CELLS(int(VAL(DOCELL_GLA.CELLS(4,2).VALUE)),19).VALUE


END SUB
